package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author labdessw04
 */
public class Skins extends javax.swing.JFrame {

       FondoPanel fondo = new FondoPanel();
       
       
    private ImageIcon iJugar;
        private ImageIcon iTiempo;

   
    private ImageIcon iBlanco, iAmarillo, iAzul, iNegro, iVaquera;
    private ImageIcon iDimAux;

    /**
     * Creates new form Skins
     */
    public Skins() {
        
        this.setContentPane(fondo);
        initComponents();
                
        // cargar imagen      
        iBlanco = new ImageIcon("src/imagenes/blanco.png");
        
        //Redimensionar imagen
        iDimAux = new ImageIcon(
                iBlanco.getImage()
                        .getScaledInstance(60, 60, Image.SCALE_AREA_AVERAGING)
        );
        
        // inserta imagen al botón
        jButton1.setIcon(iDimAux);
        jButton1.setContentAreaFilled(false);
        
        // cargar imagen      
        iAmarillo = new ImageIcon("src/imagenes/amarillo.png");
        
        //Redimensionar imagen
        iDimAux = new ImageIcon(
                iAmarillo.getImage()
                        .getScaledInstance(60, 60, Image.SCALE_AREA_AVERAGING)
        );
        
        // inserta imagen al botón
        jButton2.setIcon(iDimAux);
        jButton2.setContentAreaFilled(false);
        
        // cargar imagen      
        iNegro = new ImageIcon("src/imagenes/negro.png");
        
        //Redimensionar imagen
        iDimAux = new ImageIcon(
                iNegro.getImage()
                        .getScaledInstance(60, 60, Image.SCALE_AREA_AVERAGING)
        );
        
        // inserta imagen al botón
        jButton3.setIcon(iDimAux);
        jButton3.setContentAreaFilled(false);
        
        // cargar imagen      
        iVaquera = new ImageIcon("src/imagenes/vaquera.png");
        
        //Redimensionar imagen
        iDimAux = new ImageIcon(
                iVaquera.getImage()
                        .getScaledInstance(60, 60, Image.SCALE_AREA_AVERAGING)
        );
        
        // inserta imagen al botón
        jButton4.setIcon(iDimAux);
        jButton4.setContentAreaFilled(false);
        
        // cargar imagen      
        iAzul = new ImageIcon("src/imagenes/azul.png");
        
        //Redimensionar imagen
        iDimAux = new ImageIcon(
                iAzul.getImage()
                        .getScaledInstance(60, 60, Image.SCALE_AREA_AVERAGING)
        );
         // inserta imagen al botón
        jButton5.setIcon(iDimAux);
        jButton5.setContentAreaFilled(false);
        
        
         iTiempo = new ImageIcon("src/imagenes/tiempo.png");      
        
        iDimAux = new ImageIcon(
        iTiempo.getImage()
                .getScaledInstance(150, 150, Image.SCALE_AREA_AVERAGING)
        );
        jLabel2.setIcon(iDimAux);   
        
        
        // Imagen de bomberman vaquero
        iJugar = new ImageIcon("src/imagenes/jugar.png");      
        
        iDimAux = new ImageIcon(
        iJugar.getImage()
                .getScaledInstance(350, 200, Image.SCALE_AREA_AVERAGING)
        );
        jLabel3.setIcon(iDimAux);                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jButton4)
                            .addGap(129, 129, 129)
                            .addComponent(jButton5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(108, 108, 108)
                            .addComponent(jButton2)
                            .addGap(113, 113, 113)
                            .addComponent(jButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Skins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Skins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Skins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Skins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Skins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {
    
    private Image imagen;
    
        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/imagenes/fondoSkins.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque (false);

            super.paint(g);
        }
    
    }
}